*------------------------------------------------------------*;
* Smpl2: Create random sample;
*------------------------------------------------------------*;
data EMWS3.Smpl2_DATA(label="Sample of EMWS3.FIMPORT_train.");
set EMWS3.FIMPORT_train;
retain _seed_ 12345;
label _dataobs_ = "%sysfunc(sasmsg(sashelp.dmine, sample_dataobs_vlabel, NOQUOTE))";
drop _sample_count_ _seed_ _genvalue_;
call ranuni(_seed_, _genvalue_);
if _sample_count_ < 4128 then do;
if _genvalue_*(20640+1 - _N_) <= (4128 - _sample_count_) then do;
_dataobs_ = _N_;
_sample_count_ + 1;
output;
end;
end;
run;
quit;
